version: '3'
services:
  backend:
    build: ./backend
    container_name: backend-uav-flight-analysis
    ports:
      - 8000:8000
  frontend:
    build: ./frontend
    container_name: frontend-uav-flight-analysis
    ports:
      - 5173:5173
    depends_on:
      - backend