# --------------
# Config of OnBoard SDK
# --------------

DATA_FREQUENCY_ONBOARDSDK = 200

ONBOARD_SDK_ALTITUDE_FUSIONED_INDEX = 3
ONBOARD_SDK_ALTITUDE_BAROMETER_INDEX = 4
ONBOARD_SDK_HEIGHT_HOMEPOINT = 5
ONBOARD_SDK_HEIGHT_FUSION = 6
ONBOARD_SDK_GPS_FUSED_LATITUDE_INDEX = 7
ONBOARD_SDK_GPS_FUSED_LONGITUDE_INDEX = 8
ONBOARD_SDK_GPS_FUSED_ALTITUDE_INDEX = 9
ONBOARD_SDK_GPS_LONGITUDE_INDEX = 10
ONBOARD_SDK_GPS_LATITUDE_INDEX = 11
ONBOARD_SDK_GPS_ALTITUDE_INDEX = 12

# ----------------

AIRDATA_GPS_LONGITUDE_INDEX = 3
AIRDATA_GPS_LATITUDE_INDEX = 2
AIRDATA_GPS_ALTITUDE_INDEX = 7
